server:
  port: 7000
  servlet:
    context-path: /itmp
spring:
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
    resources:
      static-locations: classpath:/templates/,classpath:/static/
  application:
    name: itmp
  datasource:
    # 数据源
    url: jdbc:mysql://127.0.0.1:3306/micro_iam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      # 服务注册发现
      discovery:
        enabled: false # 如果不想使用 Nacos 进行服务注册和发现, 设置为 false 即可
        server-addr: 127.0.0.1:8848
        # server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850 # Nacos 服务器地址
        #namespace: 1bc13fd5-843b-4ac0-aa55-695c25bc0ac6
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
